---
title: "T4T Test"
author: "Hayden Waterstreet"
date: "2/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We're learning how to do R-stuff today
```{r}

library(curl)

rawdata <- curl("https://raw.githubusercontent.com/rhw629/tit_4_tat/master/t4t_quick-look_SUTS.csv")


rawdata <- read.csv(rawdata, header = TRUE, sep = ",", stringsAsFactors = TRUE)


head(rawdata)
#there were unnecessary columns 
rawdata <- rawdata[-c(15:26)]

head(rawdata)
 #going to separate into species now
wonder_woman <- rawdata[rawdata$SPP == "form",]
head(wonder_woman)

tippie <- rawdata[rawdata$SPP == "lat",]
head(tippie)

#there were unnecesary rows
rawdata <- rawdata[-c(11:987),]


```


### let's start analysis on **fish** *data* ***yo***

```{r}

"total sections" <- rowSums(rawdata[5:14])

cbind(rawdata)

head(rawdata)

#going to sum up total counts for each fish

rowSums(rawdata[5:14])
total_count <- rowSums(rawdata[5:14])

rowSums(rawdata[5:14])

tippie <- cbind(tippie, rowSums(tippie[5:14]))
wonder_woman <- cbind(wonder_woman, rowSums(wonder_woman[5:14]))

newdata1 <- cbind(rawdata, rowSums(rawdata[5:14]))

#now to find the average count of each fish

section_average_fish <- function(section_avg) {section_avg/10}

lat_fish_average <- section_average_fish(tippie$`rowSums(tippie[5:14])`)

tippie2 <- cbind(tippie, lat_fish_average)
#ignore tippie2, test to see if function would work
tippie <- cbind(tippie, lat_fish_average)

form_fish_average <- section_average_fish(wonder_woman$`rowSums(wonder_woman[5:14])`)

wonder_woman <- cbind(wonder_woman, form_fish_average)

#now to calculate average time spent in each section across the whole species

mean(tippie$SEC1)

tippie2 <- cbind(tippie2, lapply(tippie2[5:14], mean))
tippie2

Total_count_lat <- rowSums(tippie[5:14])
Total_count_form <- rowSums(wonder_woman[5:14])

tippie <- cbind(tippie, Total_count_lat)
wonder_woman <- cbind(wonder_woman, Total_count_form)

percent_individual <- lapply(tippie[5:14], function(x) {x/Total_count_lat}) 
Percent_individual_form <- lapply(wonder_woman[5:14], function(x) {x/Total_count_form})

tippie <- cbind(tippie, percent_individual)
wonder_woman <- cbind(wonder_woman, Percent_individual_form)

things <- apply(tippie[18:27], 2, mean)
things2 <- apply(tippie[18:27],2, mean)
stuffs2 <- apply(wonder_woman[18:27], 2, mean)

percent_lat <- things2*100
percent_form <- stuffs2*100


x <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

ggplot_frame2 <- data.frame(x, percent_lat, percent_form)


                 
```



```{r}

library(ggplot2)

ggplot(data = ggplot_frame2,  aes(x = x)) + geom_line(aes(y = percent_form, color = "amazon")) + geom_line(aes(y = percent_lat, color = "sailfin")) + xlab("Section Number") + ylab("Percent Frequency") + ggtitle("Predator Inspection & Sociability") + geom_point(aes(y = percent_form, color = "amazon")) + geom_point(aes(y = percent_lat, color = "sailfin")) + scale_x_continuous(breaks = scales::pretty_breaks(n = 10))


```